import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import NavBar from './components/NavBar'
import Rides from './components/Rides'
import useFetch from './hooks/useFetch'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* NavBar */}
      <NavBar />

      {/* Rides */}
      <Rides />

    </div>
  )
}

export default Home
