import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { RideData, UserData } from '../Functions/GlobalFunctions'
import NavBar from '../components/NavBar'
import Rides from '../components/Rides'

const Home: NextPage = () => {

  // Variables
  let userData:any = UserData()
  let res:any = RideData(userData)
  //Sorted and Filtered Ride Data
  let data = {
    nearestRideData: res.nearestRideData,
    upComingRideData: res.upComingRideData,
    pastRideData: res.pastRideData,
  // Locations Filtered based on Ride Type
    nearestloc: res.nearestloc,
    upComingloc: res.upComingloc,
    pastloc: res.pastloc,
  }

  return (
    <div>
      <Head>
        <title>Edvora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* NavBar */}
      {userData && <NavBar userData = {userData}/>}

      {/* Rides */}
      {data && <Rides data = {data}/>}

    </div>
  )
}

export default Home
